# Generated by Django 4.2.11 on 2026-04-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("convention", "Convention annuelle"),
                            ("seminar", "Séminaire"),
                            ("workshop", "Atelier"),
                            ("conference", "Conférence"),
                            ("campaign", "Campagne de sensibilisation"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("location", models.CharField(max_length=300, verbose_name="Lieu")),
                ("start_date", models.DateTimeField(verbose_name="Date de début")),
                ("end_date", models.DateTimeField(verbose_name="Date de fin")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/", verbose_name="Image"
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Places disponibles"
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais d'inscription (FCFA)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription événement",
                "verbose_name_plural": "Inscriptions événements",
                "ordering": ["-created_at"],
            },
        ),
    ]
