# Generated by Django 4.2.11 on 2026-04-05 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tombola.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tombola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=2000,
                        max_digits=10,
                        verbose_name="Prix du ticket (FCFA)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tombola/",
                        verbose_name="Image",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Date de début")),
                ("end_date", models.DateTimeField(verbose_name="Date de fin")),
                ("draw_date", models.DateTimeField(verbose_name="Date du tirage")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "À venir"),
                            ("active", "En cours"),
                            ("drawing", "Tirage en cours"),
                            ("completed", "Terminée"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tombola",
                "verbose_name_plural": "Tombolas",
                "ordering": ["-draw_date"],
            },
        ),
        migrations.CreateModel(
            name="TombolaPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(default=1, verbose_name="Rang")),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Titre du lot"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tombola/prizes/",
                        verbose_name="Image du lot",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="Valeur estimée (FCFA)",
                    ),
                ),
                (
                    "tombola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes",
                        to="tombola.tombola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot",
                "verbose_name_plural": "Lots",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="TombolaTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        default=tombola.models.generate_ticket_number,
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de ticket",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mtn", "MTN Mobile Money"),
                            ("orange", "Orange Money"),
                            ("moov", "Moov Money"),
                        ],
                        max_length=20,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Numéro de paiement"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Payé")),
                (
                    "is_winner",
                    models.BooleanField(default=False, verbose_name="Gagnant"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tombola_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prize_won",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="winner_ticket",
                        to="tombola.tombolaprize",
                    ),
                ),
                (
                    "tombola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tombola.tombola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket tombola",
                "verbose_name_plural": "Tickets tombola",
                "ordering": ["-created_at"],
            },
        ),
    ]
