# Generated by Django 4.2.11 on 2026-04-05 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("ghana", "Ghana"),
                            ("nigeria", "Nigeria"),
                            ("south_africa", "Afrique du Sud"),
                            ("kenya", "Kenya"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Destination",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "duration",
                    models.CharField(
                        help_text="Ex: 4 semaines, 3 mois",
                        max_length=100,
                        verbose_name="Durée",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Coût (FCFA)"
                    ),
                ),
                (
                    "partner_institution",
                    models.CharField(
                        max_length=300, verbose_name="Établissement partenaire"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="programs/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Places disponibles"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "highlights",
                    models.TextField(
                        blank=True,
                        help_text="Un point par ligne",
                        verbose_name="Points forts",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="Un prérequis par ligne",
                        verbose_name="Prérequis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Programme d'immersion",
                "verbose_name_plural": "Programmes d'immersion",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgramRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn", "MTN Mobile Money"),
                            ("orange", "Orange Money"),
                            ("moov", "Moov Money"),
                        ],
                        max_length=20,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de paiement"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant payé (FCFA)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription programme",
                "verbose_name_plural": "Inscriptions programmes",
                "ordering": ["-created_at"],
                "unique_together": {("program", "member")},
            },
        ),
    ]
