# Generated by Django 4.2.11 on 2026-04-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("immersion", "Séjour d'immersion"),
                    ("camp", "Camp de vacances"),
                    ("exchange", "Échange scolaire"),
                    ("homestay", "Famille d'accueil"),
                    ("teacher_training", "Formation enseignants"),
                ],
                default="immersion",
                max_length=20,
                verbose_name="Type de programme",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="transport_partner",
            field=models.CharField(
                blank=True,
                help_text="Ex: STC Bus (tarif réduit)",
                max_length=200,
                verbose_name="Partenaire transport",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="destination",
            field=models.CharField(
                choices=[
                    ("ghana", "Ghana"),
                    ("nigeria", "Nigeria"),
                    ("burkina", "Burkina Faso"),
                    ("south_africa", "Afrique du Sud"),
                    ("kenya", "Kenya"),
                    ("other", "Autre"),
                ],
                max_length=20,
                verbose_name="Destination",
            ),
        ),
    ]
